language: python
python:
  - "3.5"
install:
  - pip install python-coveralls
  - pip install coverage       # Add me to install coverage.py
# command to run tests
script: 
  - make test
after_success:
  - coveralls
